# The name of this file shouldn't be changed, or else the Setup Assistant won't detect it
sensors:
  - filtered_cloud_topic: filtered_cloud
    max_range: 1.3                    # ← 传感器检测距离
    max_update_rate: 5.0              # ← 传感器更新频率
    padding_offset: 0.05              # ← 障碍物膨胀偏移
    padding_scale: 1.0                # ← 障碍物膨胀比例
    point_cloud_topic: /camera/depth/color/points_filtered
    point_subsample: 1                # ← 点云采样率
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  # - far_clipping_plane_distance: 5.0
  #   filtered_cloud_topic: filtered_cloud
  #   image_topic: /camera/depth/image_rect_raw
  #   max_range: 5.0
  #   max_update_rate: 1.0
  #   near_clipping_plane_distance: 0.3
  #   padding_offset: 0.03
  #   padding_scale: 4.0
  #   point_cloud_topic: /camera/depth/color/points
  #   point_subsample: 1
  #   queue_size: 5
  #   sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
  #   shadow_threshold: 0.2